team-apm/apm

.eslintrc
package.json
src/index.html
src/main.js
src/preload.js
yarn.lock

Add the feature to manage the version of AviUtl and exedit.
- Check the latest version
- Choose installation path
- Download a specific version
#1
This will solve the difficulty in installing AviUtl and exedit.
- OS: Windows 10 Home
- Version: 21H1

Add managing the version of AviUtl & exedit

---

README.ja.md
README.md
package.json
src/main.js
yarn.lock

Add auto updating feature.
#6
Be able to use the latest version always.
- OS: Windows 10 Home
- Version: 21H1

feat: add auto updating

---

src/core/core.js
src/index.html
src/lib/replaceText.js
src/preload.js

Modularize scripts and make them easier to read.
Close #9
As this project grows more, the script files will be more complicated.
Version: 21H1

refactor: modularize scripts

---

src/core/core.js
src/preload.js

Check whether a program is installed on launching and on changing installation path.
Close #12
It was unclear whether the program was really installed or not.
Version: 21H1

feat: check whether a program is installed on launching and on changing installation path

---

src/main.js

Add a browser system to download plugins or scripts.
Close #16 
I want to download plugins or scripts on apm.
Version: 21H1

feat: add a browser system to download plugins

---

package.json
src/core/core.js
src/index.css
src/index.html
src/lib/unzip.js
src/main.js
src/plugin/plugin.js
src/preload.js
yarn.lock

Added features to manage plugins.
- Checking new version
- Show details of plugins
- Installing plugins
- Downloading zip archive
- Unzipping the archive
- Copying the files
- Using an installer
- Uninstalling plugins
Close #2 
This change will make it easy to install or uninstall AviUtl's plugins.
Version: 21H1

Add features to manage plugins

---

src/index.css
src/index.html
src/preload.js
src/script/script.js

- Checking new version
- Show details of scripts
- Installing scripts
- Downloading zip archive
- Unzipping the archive
- Copying the files
- Using an installer
- Uninstalling scripts
Close #3 
This change will make it easy to install or uninstall AviUtl's scripts.
Version: 21H1

feat: add a feature to manage scripts

---

src/core/core.js

Changed the name of the directory for core files from Core to core
Close #22 
It seems that lowercase is better.
Version: 21H1

refactor: change the name of the directory for core files from Core to core

---

src/plugin/plugin.js

Rewrite the jsdoc of 'setPluginsList' in plugin.js.
Close #23 
The jsdoc of 'setPluginsList' in plugin.js is wrong.
That would cause a misunderstanding.
Version: 21H1

docs: rewrite the jsdoc of 'setPluginsList' in plugin.js

---

src/index.html

Change button text to simplify it.
Close #30 
The button text is too long and the buttons do not appear in a row.
Version: 21H1

chore: change button text to simplify it

---

src/core/core.js
src/index.html
src/plugin/plugin.js
src/preload.js
src/script/script.js
src/setting/setting.js

Create a setting pane and be able to change the version file URL.
Close #19 
If I can't edit my version file, I still want to be able to use this app.
Version: 21H1

feat: add support for changing the URL to get the data files

---

src/core/core.js
src/plugin/plugin.js
src/script/script.js
src/setting/setting.js

Change the color of the button on success.
Close #33 
It is difficult to know if the program has been successfully executed.
Version: 21H1

style: change the color of the button to change on success

---

src/index.css
src/index.html

Use the grid system of Bootstrap for the plugin/script's detail panel.
Close #38 
I think the description section in the details is hard to read, especially a long description.
Version: 21H1

style: use the grid system of Bootstrap for the plugin/script's detail panel

---

src/script/script.js

Change the name of the type which is for the track bar
fix #42
Version: 21H1

fix: fix the name of type of track bar

---

src/main.js

Fixes the screen going blank when the "Maximize" button is pressed immediately after starting APM. 
I don't know why, but it seems to happen [when I run `hide()` and `show()` in sequence.](https://github.com/electron/electron/issues/21753)

fix(main.js): fix for splash screen clearing

---

src/index.html
src/main.js
src/preload.js
src/setting/setting.js

Adds the feature to adjust the zoom of the display.
Close #46 
Version: 21H1

feat: add the feature to adjust the zoom of the display

---

package.json
src/main.js
yarn.lock

Saves the data of the development version and the production version in different locations. This allows you to develop a new version of the product without having to change the data of the product in use.

feat(userData&Store): separate data for production and development

---

package.json
src/main.js
yarn.lock

Make DevTools available in the development environment.
The DevTool can be opened by pressing F12. For detailed usage, please refer to electron-debug.
This is useful for checking errors that occur in the renderer process or for examining the UI design.
DevTools is available in the development version, but not in the packaged version.

feat: enables DevTools in the development environment

---

package.json
src/index.css
src/index.html
src/plugin/plugin.js
src/script/script.js
yarn.lock

To make it easier to find plugins and scripts, add sorting and filtering functions.
resolves #40, resolves #41
- Filter the plugins by the search field.
- Sort plugins by pressing the table header.
- The same goes for scripts.

feat: sortable and filterable tables

---

CONTRIBUTING.ja.md
CONTRIBUTING.md
src/about.html
src/main.js

Adds contributors' credits.
Contributors, please add your name to credit, if you are OK.
Close #59
Version: 21H1

feat: add contributors' credits

---

src/index.css
src/index.html
src/plugin/plugin.js
src/script/script.js

Improved the appearance of the table. It includes highlighting the selected row, pinning the table header, and other minor fixes.
UI design is a matter of preference. I'm open to suggestions.

feat: improve appearance of the table

---

src/index.html

I forgot to apply #62 to the script side, so I fixed it.
fix #61

fix: fix scrolling the detail panel for a script

---

src/core/core.js
src/lib/buttonTransition.js
src/plugin/plugin.js
src/script/script.js
src/setting/setting.js

Add a library to transition a button and change to use it.
#70 (Doesn't close it.)
Reference #70 
Version: 21H1

refactor: add a library to transition a button and change to use it

---

src/index.css

I take more padding on the left and right of the tables.
@mitosagi I'd like you to feedback on this.
When I made the table wider, it looked a little cramped.

refactor: add padding to the left and right of the tables

---

src/lib/parseXML.js

#57 
Perhaps #52 
Version: 21H1

refactor(parseXML): add a library to parse XML

---

src/core/core.js
src/plugin/plugin.js
src/script/script.js

Changes to use the library to parse XML.
Closes #57 
Version: 21H1

refactor(parseXML): change to use the library to parse XML

---

src/main.js
src/plugin/plugin.js
src/script/script.js

- Change to be able to cancel the installation.
- Fixes to not continue processing when an error occurs on searching a file.
Closes #81 
Reference #81 
Version: 21H1

fix: change to be able to cancel the installation

---

src/script/script.js

refactor(script.js): fix typos

---

src/setting/setting.js

Fixes a problem that the initialization of dataURL fails in a new APM installation.
- The default url is displayed in the setting tab even if you start it with all the apm data deleted.

fix(setting): fixed dataURL initialization process

---

src/main.js

Displays a dialog box to confirm the certificate. The text is taken from [chromium](https://source.chromium.org/chromium/chromium/src/+/main:components/strings/components_strings_ja.xtb;l=1295?q=%E3%81%93%E3%81%AE%E3%82%B5%E3%82%A4%E3%83%88%E3%81%A7%E3%81%AF%E5%8F%A4%E3%81%84%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3%E8%A8%AD%E5%AE%9A%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99&ss=chromium) (BSD-like license).
Even after merging this PR, you still cannot install the "DirectShow File Reader プラグイン for AviUtl" because the 7zip library does not support the lzh format.
fix #80
- You can open "DirectShow File Reader プラグイン for AviUtl" download site.

fix: display the certificate confirmation dialog

---

src/core/core.js
src/lib/apmJson.js
src/plugin/plugin.js
src/preload.js
src/script/script.js

Now users can keep their data even if they change the installation path.
BREAKING CHANGE: All installation information will be reset.
Closes #45 
Reference #45 
Version: 21H1

feat: change to manage versions by JSON file in installation directory

---

src/lib/apmJson.js

Write json synchronously. This should reduce the number of read and write operations happening at the same time.
The list of installed packages will be displayed correctly even right after the package installation.

fix(apmJson): write json synchronously

---

package.json
src/main.js
yarn.lock

Adds a feature that saves window position & size and restores it on starting.
Closes #96 
Reference #96 
Version: 21H1

feat: save window position & size and restore it on starting

---

CONTRIBUTING.ja.md
CONTRIBUTING.md
README.ja.md
README.md
package.json
src/about.html
src/index.html
src/splash.html

We change the name of the app from "AviUtl Plugin Manager" to "AviUtl Package Manager".
This change is to make it clear that "apm" is not only for plugins, but also for AviUtl itself, Exedit Plugin, and scripts.
BREAKING CHANGE: All settings will be lost.
Close #93 
Reference #93 
Version: 21H1

docs(App Name): change the name of the app

---

src/core/core.js
src/index.html

Make the UI easier to understand.
- Detects aviutl that has been added manually.
- Displays information to help you decide which version to install.
- Clarifies how to add packages.
You can see it visually.

feat: add descriptions to the UI

---

src/core/core.js
src/package/package.js
src/preload.js

Fixes a bug in which errors were not displayed while processing was in progress
Fixes #97
Reference #97 
Version: 21H1

fix: fix a bug in which errors were not displayed while processing was in progress

---

src/about.html

Added my name to the Contribution (a little proudly).

chore: add my name to the contributions

---

src/package/package.js

Changes to freeze the selected package while installing or uninstalling.
fixes #111
Reference #111 
Version: 21H1

fix: change to freeze the selected package while installing or uninstalling

---

src/setting/setting.js

Changes the default data repository.
Closes #112
Reference #112 
Version: 21H1

refactor: change the default data repository

---

src/core/core.js
src/index.html
src/lib/mod.js
src/lib/parseXML.js
src/package/package.js
src/setting/setting.js

Adds a feature to display update date and time of data lists.
But I don't have a good idea about its design.
So please let me know your idea if you have.
Closes #104 
Reference #104 
Version: 21H1

feat: add a feature to display update date and time

---

src/package_maker.html
src/package_maker_preload.js

Changes to the package manager.
- Support for mirror URLs
- Support for installers
- Fixes to detection of inconsistent file structures
- Other modifications
Sorry the diff is hard to see.
To make it easier to enter plugins from `rigaya` that use installer or mirror URLs.
The intended XML will be generated

feat(package maker): support for installers

---

src/core/core.js

Changes button transition of checking the latest core data.
Closes #110 
Reference #110 
Version: 21H1

refactor: change button transition of checking the latest core data

---

src/main.js

Add a button to send feedback in the upper menu.
Do you think the page opened is appropriate?
Close #117 
Reference #117 
Version: 21H1

feat: add a menu to send a feedback

---

src/package/package.js

This is a fix for a bug that prevented sorting and filtering from working when installing packages.
Install or uninstall the package with the filter and sort applied.

fix: fix for sorting and filtering

---

src/core/core.js
src/main.js
src/preload.js

I used to use `setAttribute`, so change to `value` property.
Because the codes were mixed.
Version: 21H1

Refactor some code

---

src/lib/apmJson.js
src/package/package.js

Use variable names that are easy to understand. Sorry, but there is a destructive change to `apm.json`. I wanted to get this in before release.
Since it involves destructive changes, I'm using improvement instead of refactoring.
**This PR relies on #123 .**

feat: use understandable name

---

src/core/core.js
src/preload.js

This will save you the effort of pressing the update button when you use APM for the first time. This is also to keep the installation instructions short.
This PR also contains additional commits to suppress bugs related to the timing of initialization.

feat: load repository data at first startup

---

src/index.html
src/preload.js
src/setting/setting.js

Insert the default repository when nothing is entered in the input.
Close #122 
Reference #122 
Version: 21H1

feat: insert the default repository when nothing is entered in the input

---

README.en.md
README.md

Add installation and usage instructions to the readme. I will write the English version after the Japanese version is accepted.

docs(readme): update the readme

---

docs/index.md

Initial commit for document.
#131 (Don't close)
Reference #131

docs(docs): initial commit

---

.editorconfig
src/about.html
src/index.html
src/package_maker.html

Change tab width from 4 to 2
These days, the code becomes longer and longer, so it becomes hard to read.
Reduce the tab width to reduce reading difficulty.
Version: 21H1

style: change tab width from 4 to 2

---

src/setting/setting.js

DataURL is not loaded on first launch. 
Discussed in #132 .

fix: dataURL is not loaded on first launch

---

src/about.html

Add about the license to the about page
I forgot to display the license.
Version: 21H1

docs(about): add about the license to the about page

---

src/index.html
src/lib/unzip.js
src/main.js
src/package/package.js
src/preload.js

Add a button to open the package download folder.
closes #138
Make sure that the download folder opens when you press the button after selecting the package.

feat: add a button to open the download folder

---

src/index.css
src/index.html
src/package/package.js
src/preload.js

Add filtering of packages.
If you want more options, please let me know.
Close #113
Refer to #113 
Version: 21H1

feat: add filtering of packages

---

src/core/core.js
src/index.html
src/lib/mod.js
src/lib/parseXML.js
src/package/package.js
src/preload.js
src/setting/setting.js

Supports the installation of scripts that are not included in the database.
List of things to do before merging
- Create and publish an HTML file containing a link to the script
- Consider a better name for the button.
closes #141
- You can install scripts that are not listed.
- You can uninstall installed scripts
- You can update from an existing version of APM without problems

feat: install scripts without a database 

---

yarn.lock

Update some packages
@mitosagi please check these notes
> fix value parsing issues using strnum library
I think it may fix a parser bug.
Update to v.2.4.1
Includes some changes in parsing HTML or JavaScript.
The change in parsing the HTML will make the code easier to read.

build(deps): update some packages

---

src/package_maker.html

Fixed the title of package maker.

style(package maker): correct title

---

src/index.html
src/preload.js

Collapse the buttons introduced by #142 .
- The click event will be executed correctly.

fix: reduce buttons

---

src/index.html

Improve the appearance of the main page.
- All buttons will work as before.

style(index.html): improve the main page

---

src/main.js

Change to show some windows when ready-to-show is emitted.
This is only a suggestion.

perf: change to show some windows when ready-to-show is emitted

---

src/core/core.js
src/lib/apmJson.js
src/lib/buttonTransition.js
src/lib/mod.js
src/lib/parseXML.js
src/lib/unzip.js
src/main.js
src/package/package.js
src/setting/setting.js

- Make window icons common.
- Cut out functions in `module.exports` to the outside.

Refactor icons and modules

---

src/about_preload.js
src/main.js
src/package_maker_preload.js
src/preload.js

Add the feature to log uncaught exceptions and exit.
If you want more information, you can add a log.

feat(log): add the feature to log uncaught exceptions and exit

---

src/package/package.js
src/package/packageUtil.js

To make the code easier to read, move the functions not related to the UI from package.js to packageUtil.js.
- Operations that can be performed from the package tab will still work as before.

Refactoring package.js

---

src/core/core.js
src/lib/parseXML.js
src/package/package.js
src/package/packageUtil.js

Supports dependency features.
**This PR depends on the following PRs.**
- #153 
- https://github.com/hal-shu-sato/apm-data/pull/28
In fact, I was aiming for a feature that would allow to install the entire dependency. However, it seemed difficult, so I simplified the implementation.
- Packages that do not have a parent installed will be marked with ❗.
- ⚠️ will be displayed for packages that cannot be installed in the installed version of aviutl or exedit.
- If a package cannot be installed because another version of the package is installed, ⚠️ will be displayed.
- Filtering by installation state still works.

Support dependencies

---

src/core/core.js
src/lib/parseXML.js
src/package/package.js
src/package/packageUtil.js
src/preload.js

Add links to install the missing dependencies.
**This PR depends on the following PRs.**
- #154
- After you install "マイクラスキン", you will see links to install the missing dependencies.
- Click the link to install the package.

feat: add link to install missing dependencies

---

src/index.html

Improved the appearance of the settings page and the margins of the main page.
- All buttons will work as before.

style(index.html): improve the settings page

---

README.en.md

Update the English version of the readme.

docs(readme): update English readme

---

package.json
src/about.html
src/index.css
src/index.html
src/package/package.js
src/package_maker.html
src/splash.html
yarn.lock

Use twemoji for the emoji in the package list. Also, update CSP and remove "X-Content-Security-Policy" which does not work on chromium.

feat: use twemoji

---

src/core/core.js
src/package/package.js

Replace throw with `log.error` & `return`.
This reduces the chance of catching expected errors and showing error messages.

refactor: replace throw with log.error & return

---

README.en.md
README.md

Add links to the latest release page in README.
I'll merge this soon.

docs(README): add links to the latest release page

---

src/core/core.js
src/main.js
src/preload.js

Set the default installation path.
A typical installer comes with a default path, so you can simply click the "Continue" button to install the software. However, this is not the case with apm.
- When changing from the default folder to a different folder, if the folder is empty, it will be deleted.
- Data will be downloaded as before at the first startup.

feat: default installation path

---

package.json
src/index.html
src/main.css
src/package_maker.html
yarn.lock

Supports dark themes. 
The color of the window's title bar remains white even in dark mode, but this is difficult to fix.
```
https://github.com/electron/electron/issues/23479
/* To prevent backlinks */
```
closes #194

feat: supports dark themes

---

package.json
src/index.css
src/index.html
src/main.css
src/package/package.js
src/package/packageUtil.js
src/package_maker.html
yarn.lock

Visualize package data using a list instead of a table. This allows you to view the package data without any problems even in small window sizes.
- #198

feat: improvement of package list

---

src/main.js

Improve stability of main.js using constant variables.
Perhaps #143 
The app was launched correctly.

refactor: improve stability of main.js

---

src/core/core.js

Make the install buttons clickable for usability.
The buttons worked correctly.

fix: make the install buttons clickable

---

package.json
yarn.lock

Upgrade some packages.
**Bold indicates major update.**
This PR will be merged soon.
- **@commitlint/cli 14.1.0**
- **@commitlint/config-conventional 14.1.0**
- electron 14.2.0
- **eslint 8.2.0**
- **eslint-plugin-jsdoc 37.0.3**
- fast-xml-parser 3.21.1
- husky 7.0.4
- lint-staged 11.2.6
- standard-version 9.3.2
The app worked corrrectly.

build(deps): upgrade some packages

---

src/index.css

Fix sort button design on darkmode.

fix: fix sort button design

---

src/splash.css

refactor: remove unused CSS setting

---

src/main.js

Change timing of showing the splash window earlier.

perf: change timing of showing the splash window

---

src/about.html

Change style of about.html.
I'll merge this soon.

style: change style of about.html

---

src/index.html
src/main.css

Lighten the color of the selected list to make it easier to see. There are also some minor fixes to the design of the settings page.

feat: change the UI colors to improve readability

---

.github/workflows/nodejs.yml

Change to run Node CI on pull requests.
This PR will be merged soon.

ci(nodejs.yml): change to run Node CI on pull requests

---

src/lib/parseXML.js
src/package/package.js

Show original developers.
Close #174 
Refer to #174 
I thought hal-shu-sato/apm-data#36 is better, so I use it.

feat: show original developers

---

src/lib/apmJson.js
src/lib/mod.js

This is a minor fix to the JSDocs.

refactor: fix some JSDocs

---

src/lib/parseXML.js
src/package/package.js

Add an option to make the version a date, see https://github.com/hal-shu-sato/apm-data/issues/34#issuecomment-962547027 .
This is not a destructive change. The current apm will display the version as undefined because the latestVersion type becomes object when the attribute is added. However, it does not make the previously available packages unavailable.
https://github.com/hal-shu-sato/apm-data/issues/34
- Create an xml containing the `continuous="true"` attribute to `latestVersion` and install it.

feat: add the option to make the version a date

---

src/main.js
yarn.lock

Update these packages:
- electron 14.2.1
- electron-dl 3.3.0
From electron-dl 3.3.0, the `overwrite` option was added, so the default behavior was changed to add a number to the end of the file name if the file exists.

Update some packages

---

package.json
yarn.lock

Update lint-staged 12.0.1.
Specify the version of Node.js.
I want to align the Node.js version with electron to make the working environment closer.

Update lint-staged & Specify the version of Node.js

---

README.md
docs/index.md

Update the download links in the documentation.

docs: update the download link

---

package.json
src/core/core.js
src/lib/getHash.js
src/lib/parseXML.js
src/main.js
src/package/package.js

Uses hashes to guess the version of the installed program. This makes it easier for people who already have AviUtl installed to use apm.
- https://github.com/hal-shu-sato/apm-data/pull/43
https://github.com/hal-shu-sato/apm-data/pull/43 must be loaded in apm.
- If you start apm after deleting apm.json, the version will still be displayed.

feat: estimate the version from the hash

---

.github/dependabot.yml

Add a Dependabot setting file.

ci(Dependabot): add a Dependabot setting file

---

.github/ISSUE_TEMPLATE/config.yml

Add the Google form to the issue templates.
If you have any ideas, please let me know.

chore: add the Google form to the issue templates

---

docs/_layouts/default.html

Add a button link to the release notes.

docs: add a button link to the release notes

---

forge.config.js
package.json
util/sri.js

Add a utility to generate SRI made by @mitosagi.
I fix a little and add to the yarn script.
hal-shu-sato/apm-data/pull/47

chore: add a utility to generate SRI

---

src/lib/parseXML.js

Fix a bug that caused interruptions when parsing file elements failed.

fix: fix a bug that caused interruptions when parsing file elements failed

---

src/index.html
src/package_maker.html

style: fix html files with prettier

---

src/core/core.js
src/lib/parseXML.js

Supports data v2 `core.xml`. Please use the data v1 `packages_list.xml` and `mod.xml` for testing.
- #235
- If you start apm after deleting `apm.json`, the correct version will be reconfigured.

feat: support for data v2 core.xml

---

src/core/core.js
src/lib/parseXML.js
src/package/package.js
src/preload.js

Supports data v2 `mod.xml`. Please use the data **v1** `packages_list.xml` and data **v2** `core.xml` for testing.
- #243
- #235
- You can get the update date of the package.

feat: support for data v2 mod.xml

---

package.json
src/core/core.js
src/index.html
src/lib/parseXML.js
src/main.js
src/migration/migration1to2.js
src/package/package.js
src/package/packageUtil.js
src/preload.js
src/setting/setting.js
yarn.lock

Supports data v2, upgradable from v1. I will not implement integrity in this PR.
- #243
- #244
- #245
- It works fine with a clean install.
Update from v1
- The URL from which data is retrieved has been updated.
- The cache of v1 will be deleted.
- Packages added by the script installation feature not listed in the table will be correctly inherited.
- The repository URL in apm.json is updated.
- The id in the apm.json will be updated to that of v2.
- Version numbers are added to electron-store and apmJson.

feat: support for data v2 packages.xml and migration

---

src/core/core.js
src/lib/buttonTransition.js
src/package/package.js
src/preload.js
src/setting/setting.js

Remove btn paramater from many functions
- Close #251 
Refer to #251 
All buttons work.

refactor: remove btn paramater from many functions

---

src/main.js

- Add a menu to open Google Form.
Creating issues on GitHub needs a GitHub account, so Google Form makes it easier to send feedback.
Open the page correctly.

feat: add a menu to open Google Form

---

src/core/core.js
src/lib/integrity.js
src/lib/parseXML.js
src/package/package.js

Detect package versions using integrity.
- #235
- #245
Even if you remove apm.json, packages that match the integrity will be added again.

feat: detect package versions

---

README.en.md
README.md

Add contributors' names in README.

docs(README): add contributors in README

---

src/package_maker.html
src/package_maker_preload.js

Make the package maker compatible with data v2.

feat: update Package Maker

---

src/index.html
src/package/package.js

This is a fix for the problem that #263 slows down the execution time of setPackagesList by 120 ms. It also includes refactoring.
- The execution time of setPackagesList will be faster.
- The apm will work as before.

fix: fix for setPackagesList

---

src/package/package.js

Updating an item in listJS also updates the DOM, which is a non-trivial behavior. I'll leave a comment for future reference.
- #265

refactor(package.js): add a comment about listJS

---

src/main.js
src/migration/migration1to2.js

Add backups and logs to the migration to data v2
- The `apm.json` will be copied to `Data\migration1to2` when the migration starts.

feat: add backups and logs to the migration

---

src/main.js

- Prevent too many event handlers.
All functions work.

perf: prevent too many event handlers

---

src/core/core.js
src/index.html
src/package/package.js
src/package/packageUtil.js
src/preload.js
src/setting/setting.js

Improve UI.
- Shorten text in buttons.
- Adjust the design of the packages' list.
- Combine the buttons to configure the data repository into one.
All functions work.

refactor(UI): improve UI

---

src/core/core.js
src/lib/convertId.js
src/lib/parseXML.js
src/migration/migration1to2.js
src/preload.js

Add the feature to convert IDs at startup and when changing the installation path.
- #245
- hal-shu-sato/apm-data#81
It has run at startup and when changing the installation path.

feat(convertId): add a feature to convert IDs

---

src/setting/setting.js

Initialization fails due to missing function arguments. URL removal is for refactoring.

fix(setting.js): fix for initialization failure

---

src/lib/parseXML.js

Implement the output of `<releases>` including SRI information in XML export.
- #310
There is currently no code path where this feature is used.
- setPackages() was run in `parseXML.js:375` and the results were visually verified.

feat: support releases tag in XML export

---

src/core/core.js
src/preload.js

Reduce the code path by integrating the apm startup process with the folder change process.

refactor: apm startup process

---

src/lib/updatableList.js
src/package/package.js

Fixes a problem where filter, search, and sort applied to the package list were ignored when installing a package from the "Install unlisted scripts" feature. This occurs because `update()` in list.js is executed without considering the status of filter, search, and sort.
- With the filter, search, and sort applied, install the package from the "Install unlisted scripts" feature. After installation, the filter, search, and sort are still applied.

fix(list.js): fix update() in list.js

---

src/main.js
src/package/package.js

Supports 7z and rar; the archiver apm is using originally supports this format, so I just enabled it.

feat: support 7z and rar

---

src/core/core.js
src/package/package.js
src/package/packageUtil.js

Refactoring `setPackagesList()` in package.js. Also, removed the redraw feature, which has caused many bugs.
- The package list will be drawn correctly.
- The package list will be drawn correctly even after the package is installed.
- The package list will be drawn correctly even after installation of unlisted scripts.

feat: refactor setPackagesList()

---

package.json
src/lib/compareVersion.js
src/package/package.js
yarn.lock

Add the feature to indicate updatable packages.
- closes #316
- Packages that can be updated will be marked.
- toSemver() has been tested in all versions included in apm-data.
<details>
<summary>Before toSemver()</summary>
```
v1.8
v1.0
v2.5
Ver 0.1
Ver 0.2
Ver 0.1.0
v0.1.1
v0.1.0
v0.1.1(仮修正)
Ver 1.0
Ver 0.3.5
Ver 0.2b
Ver 0.4.1
Ver 0.4
Ver 0.3.1
Ver 0.5.0
Ver 0.4.0
2014/05/06
2014/04/06
2014/04/16
2013/01/08
2012/09/10
ver1.4
ver0.6
ver0.1
ver0.3
ver0.26a
ver0.9
ver0.5
ver0.5a
2021/05/23
r11
r8
最新
v0.3.0
v1.0.0
v1.0.2
v1.0.1
v0.51 beta
2014/11/17
2009/03/28
v0.3
v0.8
v0.3.25
v0.13
v0.1
v0.2beta56
v1.1
v0.3.3
v0.3rc7
0.02
v17+8
r17
0.10
5.42
6.08
7.5a+22
v9
+6
0.05
6.17
2.68
3.102
ver 1.1
v2.2
v2.2a
ver3
1.1
v01(補助), v02
v0.9b
v0.9a
v0.9
0.9b
1.0
1.0a
1.4b
v2_0.1d
v4
v1.5
v1.5a
5 …
```

feat: indicating updatable packages

---

src/lib/parseXML.js
src/package/package.js

Implement the `onlyInstall` argument to ignore files when uninstalling.
- #372

feat: support for installation-only attributes

---

SECURITY.md
docs/_config.yml

- Update some documents for v2.1.0
This PR will be merged soon.

docs: update documents

---

docs/_config.yml
docs/_layouts/default.html

- add zip download button in the website
close #416
Refer to #416 
I ran the Jekyll server on the local environment and the button was shown.

docs: add zip download button in the website

---

src/package/package.js

Fixes a bug that caused errors during direct installation of packages without integrity.
- The data added by https://github.com/hal-shu-sato/apm-data/pull/142 can be installed with the recommended batch installation function.

fix(package.js): direct installation of packages without integrity

---

.github/dependabot.yml

- Raise the dependabot's limit.
This PR will be merged soon.

ci(Dependabot): raise the dependabot's limit

---

package.json
yarn.lock

Remove external type definitions from the twemoji library. Currently twemoji defines types internally.
```
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59628
```

build(package.json): remove types/twemoji

---

src/main.ts
src/renderer/main/index.html
src/renderer/main/preload.ts

- Move apm menu to tabs.
close #418
Refer to #418

feat: move apm menu to tabs

---

src/main.ts
src/renderer/main/index.html
src/renderer/main/preload.ts

- Add notification of the update.
- Add options to disable auto-update, notify when an update is available, or download automatically.
- Change the default setting in the zip version to notification only.
- Disable the automatic download option in the zip version.
- Add the button to check an update.
close #417 
Refer to #417 
- Downgrade `version` in `package.json`.
- Launch apm.
- apm would behave as specified in the configuration.

Improve the feature about checking update and auto update

---

forge.config.js
package.json
src/main.ts

- Change repository owner in `package.json` and `forge.config.js` to team-apm.
- Fix an error around auto-update.
close #321
Refer to #321 
- Checked the feature around the auto-update.

chore: change repository owner to team-apm

---

forge.config.js
package.json
src/main.ts

I made the mistake of releasing apm a few minutes ago. If your local branch has a `v2.2.0` tag and commit, please delete them.
Sorry.
- Revert a previous commit to change the repository owner.
- Fix a bug in releasing apm.
- Change repository owner for auto-update by the alternative way.
- close #321

fix change repository owner

---

src/lib/unzip.js
src/renderer/main/package.js
webpack.plugins.js

- Fix installing a script.
- Support matcher v5.0.0 including the change of named export.
- It seems that the bug in resolving the binary path is fixed.
- Installing scripts works correctly.

fix: fix installing a script

---

docs/_config.yml

- Update download URL in docs.
- Change the repository owner in docs.
This PR will be merged immediately.

docs: update download URL and change the repository owner

---

src/lib/apmPath.ts
src/lib/convertId.ts
src/lib/modList.ts
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/setting.ts
src/renderer/package_maker/package_maker_preload.ts

Supports split `packages` data files and `scripts` data files. Also, relative paths for data files, except for `list.json`, will be available.
If apm-schema in your `node_modules` is not up to date, please run `yarn upgrade apm-schema`.
- https://github.com/team-apm/apm-data/issues/122
This PR depends on the following PR(s)
- https://github.com/team-apm/apm/pull/532
- Can handle data added by https://github.com/team-apm/apm-data/pull/182 .

feat: support for split data files

---

src/lib/shortcut.js

Specify the current working directory for the shortcut. This is required for some plugins to work.
- closes https://github.com/team-apm/apm/issues/552
- AviUtl-LocalFontPlugin launched from the shortcut worked fine.

fix(shortcut.js): specify CWD to the shortcut

---

forge.config.js
src/main.ts
src/renderer/main/core.js
src/renderer/main/index.css
src/renderer/main/index.html
src/renderer/main/package.js
src/renderer/main/preload.ts

- Add listing the nicommons IDs of the installed packages.
close #271
Refer to #271
- ~~I will add nicommons ID into the data.~~
- I tested this feature using team-apm/apm-data#190.

feat: add listing the nicommons IDs of the installed packages

---

src/renderer/main/preload.ts
src/renderer/package_maker/package_maker_preload.ts

This is a fix for a bug that prevented release builds from starting properly. See the related issue for details.
- closes #585
- Bugs have been fixed.

fix: fix ClipboardJS import

---

src/lib/convertId.ts
src/main.ts
src/renderer/main/core.js
src/renderer/main/package.js

- Fix to catch download errors.
When a file to be downloaded doesn't exist, apm stops working.

fix: catch download errors

---

src/lib/apmJson.js
src/lib/convertId.ts
src/lib/integrity.js
src/lib/modList.ts
src/lib/parseJson.ts
src/lib/shortcut.js
src/lib/unzip.js
src/main.ts
src/migration/migration1to2.js
src/migration/migration2to3.ts
src/migration/parseXML.js
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/packageUtil.js
src/renderer/main/preload.ts
src/renderer/main/setting.ts
src/renderer/package_maker/package_maker_preload.ts

- Reorder imports using VSCode.
- Change to import a named export.

Refactor imports

---

src/lib/convertId.ts
src/lib/ipcWrapper.ts
src/lib/modList.ts
src/main.ts
src/migration/migration1to2.js
src/migration/migration2to3.ts
src/renderer/about/about_preload.ts
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/packageUtil.js
src/renderer/main/preload.ts
src/renderer/main/setting.ts
src/renderer/package_maker/package_maker_preload.ts

- Make ipcWrapper to define types.
All features work as before.

refactor: make ipcWrapper

---

src/renderer/main/index.html

The tab names are changed to Japanese. In addition, the design of the "Others" page will be improved.
- The modified buttons work properly.

feat(index.html): improve UI added in v3

---

src/lib/apmJson.js
src/main.ts
src/migration/migration2to3.ts
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/packageUtil.js
src/renderer/main/setting.ts

- Delete unnecessary `else`.
- Refactor error handling.
- Use early return and add error logging.
- Some edits may improve performance.

Refactor Error Handling

---

src/renderer/main/common.ts
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/packageUtil.js

- Make installation and counting verification common.

refactor: make installation and counting verification common

---

src/renderer/main/common.ts
src/renderer/main/core.js
src/renderer/main/package.js
src/renderer/main/packageUtil.js

- Reorder imports.
- Change to import a named export.
- Make `ipcWrapper`.
- Delete unnecessary else.
- Refactor error handling.
- Use early return and add error logging.
- Some edits may improve performance.
- Make installation and counting verification common.

Refactoring

---

src/lib/updatableList.js
src/renderer/main/index.html
src/renderer/main/package.js
src/renderer/main/packageUtil.js

Set the default package sort order and add a button to filter scripts.
- #404
- Confirmed filtering operation.

feat: sort packages on startup

---

CONTRIBUTING.ja.md
CONTRIBUTING.md
README.en.md
README.md
docs/index.md
forge.config.js
package.json
src/main.ts
src/migration/migration1to2.js
src/renderer/main/index.html

- Change the repository owner of URLs.

fix: change the repository owner of URLs

---

src/lib/apmJson.js

- reduce the error logs of ENOENT.

refactor: reduce the error logs of ENOENT

---

src/lib/ipcWrapper.ts
src/main.ts
src/migration/migration1to2.js
src/migration/migration2to3.ts
src/renderer/about/about_preload.ts
src/renderer/main/packageUtil.js
src/renderer/main/preload.ts
src/renderer/main/setting.ts
src/renderer/package_maker/package_maker_preload.ts

- Change to set a type of dialog.
- Show an info dialog after migrating v2 to v3.
Users will not notice that the data URL is reset.

Show an info dialog after migrating v2 to v3

---

src/lib/apmJson.js

- Update data version to v3.
BREAKING CHANGE: After migration, you can't downgrade to v2.
I'll merge this PR immediately.
All features work fine.

feat: update data version to v3

---

src/main.ts
src/migration/migration2to3.ts

- Adjust the way to show a dialog.
- Change not to attach the dialog to the focused window.
- Change not to wait until the dialog is closed.

refactor: adjust the way to show a dialog

---

SECURITY.md
docs/_config.yml

- Update documents for v3.0.0.
I'll merge this PR after releasing v3.0.0.

docs: update documents for v3.0.0

---

src/lib/buttonTransition.js
src/lib/unzip.js
src/renderer/main/package.js
src/renderer/package_maker/package_maker_preload.ts

- use Nullish coalescing operator.

refactor: use nullish coalescing operator

---

src/main.ts

- Change to catch update errors.
- You can launch apm normally now if the update is failed.
- Fix #618 
Refer to #618 
I did not test this PR.
Do you know the way to reproduce the proxy environment?

fix: change to catch update errors

---

docs/_layouts/default.html
docs/assets/css/style.scss

This is a small PR to correct the coloring of the official website.

feat: improve design

---

src/main.ts
src/renderer/main.css
src/renderer/main/index.css
src/renderer/main/index.html

Brush up the UI added in v3.0 and modernize the title bar.
- Check the appearance in light and dark modes.

feat(index.html): improvement of UI

---

docs/_config.yml

- Update documents for v3.1.0.
I'll merge this PR immediately.

docs: update documents for v3.1.0

---

src/main.ts

- Change to use a conditional (ternary) operator.
- Catch more update errors.
- Add catching errors in checking update information and notifying.
- fix #618

fix: catch more update errors

---

.github/dependabot.yml

- Increase the PR limit to 20.
I'll merge this PR immediately.

ci(dependabot): increase the PR limit to 20

---

src/renderer/main/index.html
src/renderer/main/package.js

Show package dependencies.
- https://github.com/team-apm/apm-data/issues/246

feat: show dependencies

---

src/migration/migration1to2.js
src/migration/migration2to3.ts

Avoid migration on new installations. This fixes a problem where a dialog box would appear during a new installation.
- Dialog "アップデート" does not appear on new installations.

fix: avoid migration on new installations

---

src/renderer/main/core.js
src/renderer/main/index.html

Simplify the UI of the main page, with the versions of AviUtl and Exedit displayed in a clear manner.

feat: update UI on main tab

---

src/lib/apmPath.ts
src/lib/modList.ts
src/lib/safeRemove.ts
src/renderer/main/common.ts
src/renderer/main/package.js
src/renderer/package_maker/package_maker_preload.ts

Fix a bug that caused the AviUtl folder to be deleted when a package containing ` { "filename": "", "isObsolete": true },` is installed or a package containing ` { "filename": "" },` is uninstalled.
This bug currently only occurs when loading incorrectly configured package data. It has never occurred in normal use.
- Installation or uninstallation of the package containing the above settings fails.

fix: safe remove()

---

README.en.md
README.md

- Make the license section itemized.
I'll merge this PR immediately.

docs(README): make the license section itemization

---

src/lib/unzip.js

- Change code page to 932(Shift_JIS).
- Refactor: simplify pathTo7zip settings.
- fix #680

fix: Garbled filename when unzipped

---

src/renderer/main/core.ts
src/renderer/main/package.ts
src/renderer/main/setting.ts

- Fix batch installation.
By changing the value returned by `buttonTransiton.loading(btn)`, the batch installation doesn't work.

fix: fix batch installation

---

src/renderer/main/package.ts

- Fix updating package list.
- Fix #746
Refer to #746.
Confirm that the modified date was changed.

fix: fix updating package list

---

src/renderer/main/packageUtil.ts

- Change to download package lists synchronously.
- Fix #746
Refer to #746

fix: change to download package lists synchronously

---

src/main.ts

Fixed a bug introduced by c60cded898253b0d1247da2b78098c25bb2c938e that caused the error to be displayed during installation.
- closes #766
For future reference, `git bisect` was very helpful.
- #766 is resolved.

fix(main.ts): don't await loadURL

---

package.json
src/renderer/main/package.ts
yarn.lock

Hides packages with the `isHidden` attribute.
- closes #695
- https://github.com/team-apm/apm-data/pull/274
- Packages with `isHidden` attribute are not displayed
- Installed packages with `isHidden` attribute are displayed

feat: function to hide packages

---

src/renderer/main/package.ts

- Fix the problem in installing a script from a script distribution website.
This bug has been happening since I migrated to async functions.
- fix #807
Refer to #807 
I could install the scripts from the script distribution website fine.

fix: fix the problem in installing a script from a website

---

docs/_config.yml

This is an update to the download URL.

docs: update _config.yml

---

src/renderer/main/index.css
src/renderer/main/package.ts

Add the feature to switch button text according to installation status.
- Close #838
Refer to #838 
- Could install a not-installed package.
- Could update an installed package.

feat: switch button text according to installation status

---

src/renderer/main/package.ts

- Fix the text of the install button for website packages.
- #859 
Refer to #859

refactor: fix the text of the install button for website packages

---

webpack.rules.ts

- fix the problem that 7-zip is not found.
This fix is reverting a part of 50a1cd8c3d33044f24e6e76b75e17b6e89cf73f8.
Sorry for the careless update.
- fix #1018
Refer to #1018 
- AviUtl and Exedit can be installed in the production and development environment.

fix: fix the problem that 7-zip is not found

---

package.json
yarn.lock

Revert "build(deps-dev): bump electron from 21.4.1 to 23.0.0"

---

.github/workflows/build.yml

Fixed a problem with windows build timeouts in CI.
`https://github.com/yarnpkg/yarn/issues/8242`
- [] All new and existing tests passed.

ci(build.yml): fix issue where windows CI timeouts

---

.github/workflows/build.yml
.github/workflows/electronegativity.yml
.github/workflows/nodejs.yml
.github/workflows/release.yml
README.en.md
README.md
package.json

In preparation for the application of electron 23, the node version is raised to 18.
- #1189

build(package.json): change node.js version

---

src/renderer/main/package.ts

- Remove an unnecessary process.
I will merge this PR immediately.

refactor: remove an unnecessary process

---

src/main.ts

Fix apm crashes when installing after canceling installation.
- Fixes #1485
- See #1485

fix(main.ts): close only when window is present

---

src/renderer/main.css
src/renderer/main/core.ts
src/renderer/main/index.css
src/renderer/main/index.html
src/renderer/main/package.ts
src/renderer/main/preload.ts

Improved the design of the main tab and the plugins & scripts tab. Especially, usability in small window sizes is improved.
- Resize the window to make sure the design is intact.
- Check the visibility in the dark theme.

feat: UI improvement

---

.github/workflows/dependabot-auto-merge.yml

- Change to assign reviewer.
I will merge this PR immediately.

ci(GitHub Actions): change to assign reviewer

---

.github/workflows/dependabot-auto-merge.yml

- Add the job name.
I will merge this PR immediately.

ci(GitHub Actions): add the job name

---

src/main.ts
src/renderer/main.css
src/renderer/main/index.html
src/renderer/main/package.ts

The nicommons api URL has changed and will follow. Also, improvements have been made to restore the visibility that was degraded by the Darktheme update.
- Visual confirmation.

feat: update on visibility

---

docs/_config.yml
package.json

Updated the download URLs on the download page. Also, added node 20.x to the supported versions in order to run commitizen on the latest LTS.
- closes #1684

docs: update Download URLs

---

src/lib/compareVersion.ts
src/renderer/main/common.ts
src/renderer/main/core.ts
src/renderer/main/package.ts
src/renderer/main/packageUtil.ts

- https://github.com/team-apm/apm-schema/pull/149 に対するapm側のPRです。conflictsエントリを実装します。
- conflictsはバージョン範囲の絞り込みができます。必要とされていないのでdependenciesには絞り込みを実装しません。
- このPRにより https://github.com/team-apm/apm-data/issues/694#issuecomment-1878312650 の問題点1と問題点3が解決され、https://github.com/team-apm/apm-data/pull/829 をマージできるようになります。
- hebiiro/SplitWindowをインストールすると、SplitWindow.xmlがpluginsフォルダにコピーされます。
- SplitWindow.xmlの内容を編集後にhebiiro/SplitWindowを更新しても、SplitWindow.xmlの内容は失われません。
- aoytsk/autoloaderをENOENTエラーなくインストールできます。（autoloader.iniは同梱されておらずコピー処理はスキップされます。）
- https://github.com/team-apm/apm-data/pull/829 のhebiiro/UltimatePluginは"ePi/patchまたはnazono/patch<=r43_42がインストールされている場合に「インストール不可」と表示されます。（apm.json内のversionを書き換えることでほかのバージョンの場合の動作をテストできます。）

feat: Implement conflicts

---

package.json
yarn.lock

- bump commitlint and commitizen

build(deps-dev): bump commitlint and commitizen

---

.eslintrc
package.json
yarn.lock

build(deps-dev): remove eslint-config-google

---

package.json
src/main.ts
src/renderer/about/about_preload.ts
src/renderer/main/common.ts
src/renderer/main/core.ts
src/renderer/main/package.ts
src/renderer/main/packageUtil.ts
src/renderer/main/preload.ts
src/renderer/main/setting.ts
yarn.lock

- bump electron-log from 5.1.1 to version 5.2.4
- update electron-log imports and error handling

bump electron-log

---

src/lib/ipcWrapper.ts
src/renderer/main/common.ts

- add return type annotations to IPC wrapper and common functions

docs: add return type annotations to IPC wrapper and common functions

---

package.json
yarn.lock

- replace npm-run-all with npm-run-all2

build(deps-dev): replace npm-run-all with npm-run-all2

---

.github/dependabot.yml

- add React and related types to Dependabot configuration

build(deps): add React and related types to Dependabot configuration

---

package.json
yarn.lock

- bump eslint-config-prettier from 9.1.0 to 10.0.1

build(deps-dev): bump eslint-config-prettier from 9.1.0 to 10.0.1

---

.github/workflows/build.yml
.github/workflows/electronegativity.yml
.github/workflows/nodejs.yml
.github/workflows/release.yml
package.json

- update Node.js version to 'lts/*' in workflows and package.json

build: update Node.js version to 'lts/*' in workflows and package.json

---

src/lib/Config.ts
src/lib/modList.ts
src/main/main.ts
src/migration/migration1to2.ts
src/migration/migration2to3.ts
src/renderer/main/core.ts
src/renderer/main/package.ts
src/renderer/main/preload.ts
src/renderer/main/setting.ts

- replace Store with Config for improved data management across modules

replace Store with Config for improved data management across modules

---

package.json
yarn.lock

- bump electron from 27.3.2 to 33.3.1

build(deps-dev): bump electron from 27.3.2 to 33.3.1

---

src/renderer/main/package.ts

- correct date retrieval for package check date

chore: correct date retrieval for package check date

---

src/renderer/about/About.tsx
src/renderer/about/index.html
src/types/image.d.ts
webpack.renderer.config.ts

- fix to use images in React components

refactor: fix to use images in React components

---

tsconfig.json

- update target to ES2022
Electron supports ES2022 and this will fit to JIT compiler, V8.

build(tsconfig): update target to ES2022

---

forge.config.ts
src/lib/ApmJson.ts
src/lib/apmPath.ts
src/lib/convertId.ts
src/lib/getHash.ts
src/lib/integrity.ts
src/lib/modList.ts
src/lib/parseJson.ts
src/lib/shortcut.ts
src/lib/unzip.ts
src/main/main.ts
src/migration/migration1to2.ts
src/migration/migration2to3.ts
src/renderer/main/common.ts
src/renderer/main/core.ts
src/renderer/main/package.ts
src/renderer/main/packageUtil.ts
src/renderer/main/setting.ts

- update path imports to use node: prefix
I will merge this PR immediately.

refactor: update path imports to use node: prefix

---

src/main/main.ts

The problem of apm not starting is solved by comment out `titleBarOverlay: getTitleBarColor()` in `main.ts:393`. There is a problem reported in electron that the `ready-to-show` event does not fire when the `titleBarOverlay` option is enable. 
`https://github.com/electron/electron/issues/42409`
So I simply removed the event.
- fix https://github.com/team-apm/apm/issues/2038
1. Run the `make` command.
2. Run `out\make\squirrel.windows\x64\AviUtl Package Manager-3.9.1 Setup.exe`
3. apm starts normally.

fix(main.ts): remove load event
