- src/main.js
- src/splash.css
- src/splash.html
Add a splash screen while loading.
#4
Reduces the frustration of long loading times.
Version: 21H1
> feat: add splash screen in launching

- package.json
- src/core/core.js
- yarn.lock
Change to use fast-xml-parser for parsing XML.
Also, fix an single element is not supported.
Close #13
xml2js is not maintained.
Version: 21H1
> refactor: change XML parser from xml2js to fast-xml-parser

- src/core/core.js
- src/plugin/plugin.js
- src/script/script.js
Change to separate 'installedVersion' in config by the type of file they are installed on.
Close #20 
'installedVersion' in config may conflict.
Version: 21H1
> refactor: change to separate 'installedVersion' in config by the type of file they are installed on

- src/about_preload.js
- src/main.js
Change the about page preload from the send/on method to the invoke method.
Close #36 
The send/on method is difficult to use because the return value is hard to understand.
Version: 21H1
> refactor: change the about page preload from the send/on method to the invoke method

- src/core/core.js
This is a fix for a minor issue where files that have not yet been installed are displayed as installation failures.
> fix(core.js): fix the condition of the installation status display

- src/plugin/plugin.js
This is a fix for the problem that the plugin installer does not work properly when Aviutl is installed in a folder whose path contains spaces. Prevents paths from being enclosed twice in quotation marks.
> fix(plugin.js): fix handling of folders containing spaces

- src/plugin/plugin.js
- src/script/script.js
Fixes an issue where plugins such as シークバー＋ and loudness.auf cannot be installed.
This problem is caused by inconsistent data structure when parsing xml, where multiple files belonging to a plugin are parsed into an array, and single files are parsed as variables.
Make sure that シークバー＋ and loudness.auf can be installed.
> fix(plugin.js&script.js): treat a single file as an array

- src/index.html
- src/plugin/plugin.js
- src/script/script.js
Manually added plugins are now shown in the plugin list. The duplicate detection algorithm for plugins has been improved accordingly.
resolves #47
- Sometimes you want to install a plugin that does not exist in the repository.
- People who are already using Aviutl should be able to use APM without reinstalling it.
- Manually added plug-ins are displayed in gray.
- Non-installed plugins that have the same files as manually added plugins will be marked as '手動インストール済み'.
> Feat(plugin&script): work with manually added plugins

- src/plugin/plugin.js
- src/script/script.js
If you try to get the list of plugins when the plugins folder does not exist yet, an error will occur. 
Fixed a bug introduced by #56.
- The plugin list can be displayed even if the plugin folder does not exist.
> fix(plugin&script): cannot display the list of plugins

- src/core/core.js
- src/lib/buttonTransition.js
- src/plugin/plugin.js
- src/script/script.js
- src/setting/setting.js
Change to be able to display all types of buttons.
You can use all types of buttons in Bootstrap when you show a message.
#70 (Doesn't close it)
Version: 21H1
> refactor(buttonTransition): change to be able to display all types of buttons

- src/lib/apmJson.js
Change to manage versions by JSON file in installation directory
Now you can keep your data even if you change the installation path.
Close #45 
It is difficult to use because the version information is reset when the installation path is changed.
Version: 21H1
> feat: change to manage versions by JSON file in installation directory

- src/main.js
Fixes an error when destroying the browser window.
Version: 21H1
> fix: fix an error when destroying the browser window

- forge.config.js
- package.json
- src/lib/unzip.js
- src/main.js
- yarn.lock
Supports lzh files in addition to zip files. This makes it possible to install "DirectShow File Reader プラグイン for AviUtl".
**This PR contains commit #88.**
- You can install the zip plugins.
- You can install the lzh plugins.
- It works not only with `yarn start`, but also with `yarn package`.
> feat(unzip): support for lzh files

- src/plugin/plugin.js
- src/script/script.js
This is a fix for the problem that the information of installed plugins is not displayed correctly immediately after installation.
- Information about installed plugins will be displayed even immediately after installation of the plugin.
> fix: add missing await

- src/lib/parseXML.js
Automatically generates the `<type>` contained in xml when xml is loaded.
https://github.com/hal-shu-sato/apm-data/issues/1
- The xml file with `<type>` removed can be read.
> feat(parseXML): automatically generate type

- src/lib/parseXML.js
- src/package/package.js
Changes to use the path of the file specified in the archive in the data file.
This reduces the number of errors.
Closes #52 
Reference #52 
Version: 21H1
> feat: change to use the path of the file specified in the archive in the data file

- src/core/core.js
- src/lib/buttonTransition.js
- src/package/package.js
Replace the unnecessary `innerHTML` with `innerText` for the security
`innerHTML` is very strong but this means it has vulnerable.
We must reduce the number of times using `innerHTML`.
Version: 21H1
> refactor: replace the unnecessary innerHTML with innerText for the security

- src/core/core.js
- src/lib/shortcut.js
- src/main.js
- src/preload.js
Add a shortcut to aviutl.exe to the Start menu.
- #196
When you install other video editing software, you will see a shortcut in the start menu. However, this is not the case with AviUtl. I think this is one of the reasons why beginners find AviUtl difficult to use.
- When you install AviUtl, a shortcut will be created.
- If you select a folder with AviUtl, a shortcut will be created.
- If you select a folder without AviUtl, the shortcut will be removed.
- If you uninstall apm, the shortcut will also be removed.
> feat: add a shortcut to the Start menu

- src/package/package.js
Supports specifying dependencies by logical ORs; by specifying multiple ids in dependency separated by `|`, one of the ids will be required.  This is necessary to correctly specify the dependency packages for ~~CacheText~~, InputPipePlugin and SigContrastFastAviUtl after implementing multiple LSMASHWorks.
This is a breaking change. This PR by itself will not cause any problems, but after the corresponding xml release, the current release of apm will not be able to find the packages it depends on.
[packages_list.zip](https://github.com/hal-shu-sato/apm/files/7533140/packages_list.zip)
InputPipePlugin included in the attachment depends on multiple LSMASHWorks as follows. It should work the same way no matter which LSMASHWorks is installed.
```
<package>
...
<dependencies> …
```
> feat(package.js): support dependency specification by logical OR

- package.json
Add `16.x` to node engines.
I thought that Electron would use the installed node.js, but it uses the included one.
In my opinion, it's better to use `16.x`.
Yarn commands worked on both `14.x` and `16.x`.
> build(package.json): add 16.x to node engines

- src/package/package.js
In https://github.com/hal-shu-sato/apm-data/pull/70 , `auls/confirmclose` always recommends installing `ePi/aulsMemref`, regardless of the version of exedit installed. This PR determines which plugins it recommends to install based on their dependencies.
- https://github.com/hal-shu-sato/apm-data/pull/70
When `auls/confirmclose` is installed
- If you have `exedit0.92` installed, `ePi/aulsMemref` is recommended.
- If you have `exedit0.93rc1` installed, `rikky/aulsPluginsByRikky` is recommended.
> fix: fix for dependency resolution

- src/package/package.js
Immediately after installing a certain plugin, pressing the "絞り込み>インストール済み" button does not show that plugin. This happens because the installation status inside listJS has not been updated.
It is written in the description.
> fix(package.js): fix for plugin filtering

- package.json
- src/lib/apmJson.js
- src/migration/migration1to2.js
Refactor editing `apm.json`.
- Add dot-prop and change to use it.
- Change to return an object containing the data version on the first get.
All function around `apm.json` works correctly.
> Change to use dot-prop to edit apm.json

- src/lib/convertId.js
- src/preload.js
This is a fix for an issue where convert.json is downloaded at an unexpected time. if parseXML() downloads convert.json before convertId(), there will be inconsistencies in apmJson.
1. add id conversion from easymp4 to easymp4a (and update mod.xml)
2. click the Update Package Data button
Intended behavior
No change in apmJson.
Actual behavior
easymp4a is added to apmJson.
When parseXML is executed in setPackagesList(), the latest convert.json is downloaded from getIdDict. At this time, easymp4a is automatically added to apmJson because there is a file whose integrity matches.
> fix: fix for unexpected download of convert.json

- src/core/core.js
- src/lib/convertId.js
- src/lib/mod.js
- src/main.js
- src/migration/migration1to2.js
- src/package/packageUtil.js
Fixed a bug that caused cache lookups to always fail for paths with hash values appended. This bug was also hiding a bug in main.js:341 (before this commit) where json was not included, but this has been fixed as well.
The download of the xml file takes place at the same time as before. This was confirmed by logging in the ipcMain.handle('download') function.
> fix: fix for cache reuse conditions

- src/core/core.js
- src/lib/integrity.js
- src/lib/parseXML.js
Make the parser compatible with archiveIntegrity. Also, add the ability to validate archive files to core.js (not to package.js).
- #235
I will reduce the number of new features added, but I added them because they are necessary for testing the parser.
- You can install AviUtl successfully.
- If you restart apm after deleting apm.json, apm.json will be regenerated as before.
> feat: partial supoort for archive integrity

- package.json
- src/index.css
- src/index.html
- src/package_maker.html
- yarn.lock
Reduce code by introducing the bootstrap icons library. To check the increase in installer size, I did a `yarn` and `yarn make` after removing node_modules and the increase in size was 0.7MB (90.6→91.3 MB).
> refactor: add bootstrap icons library

- src/core/core.js
- src/package/package.js
- src/package/packageUtil.js
Prevents package overwriting by the batch install feature.
After performing a batch installation with MrOjii/LSMASHWorks installed, a total of two installations including pop4bit/LSMASHWorks will be saved in apmJson. This is a problematic situation. This PR is to prevent packages that have already been installed from being installed again.
**This PR must be released before https://github.com/hal-shu-sato/apm-data/issues/87 is resolved.**
See the description.
> fix: prevent package overwriting

- src/package/package.js
Script authors often distribute their packages as raw, unarchived files, and apm cannot read them.
Example: https://drive.google.com/drive/folders/1axN8BDCSGY3w1YaeUgZ4TjlU7MzwRoGI?usp=sharing
This PR makes such files installable.
- #337
After setting `packages.xml` in [packages.zip](https://github.com/hal-shu-sato/apm/files/7942927/packages.zip) as "追加データ取得先", you can successfully install "ドカベンの文字エフェクト" that appear in the package list.
> feat(packages.js): support for non-archived packages

- src/core/core.js
- src/main.js
- src/package/package.js
Check the integrity of the archive for packages that are downloaded directly by the recommended bulk installation.
- closes #235 
- closes #245
- closes https://github.com/hal-shu-sato/apm-data/issues/50
- If you click the recommended bulk install button, the package will be installed as before.
- If you click the recommended bulk install button while the cache file in `AppData` has been changed, the package will not be installed.
> feat(package.js): support for archive integrity

- src/core/core.js
Fix a bug that prevented reading old format `mod.xml`. This fix is necessary to keep the main branch releasable.
- #352
- The main branch of apm-data can be loaded without error.
> fix(core.js): support for old mod.xml

- src/core/core.js
- src/lib/parseXML.js
- src/package/package.js
- src/package/packageUtil.js
Add a flag to xml to correctly handle files that are not part of the latest version of the package.
Files with `obsolete = true`:
- Will be removed before installation
- Not copied during installation
- Not included in post-installation success checks
Packages that contain `obsolete = true` files:
- Corruption is not checked when checking installation status.
Also, remove incorrect conditional branch regarding `optional` flag
- https://github.com/hal-shu-sato/apm-data/issues/123
- It is possible to correctly update the patch.aul
> feat: support for obsolete flag of files

- src/core/core.js
- Change to make an installation directory just before installing.
Fix #388
- apm started normally.
- apm installed AviUtl, Exedit, plugins, and scripts.
> fix: make an installation directory just before installing

- src/package/package.js
Fix a bug that prevented scripts from installing dependent libraries.
Steps to reproduce
1. Install one of gometh's scripts.
2. Click on "要導入" on the right side of the installation information and you will see the error "このスクリプトは上書きインストールできません。".
- You can install libraries on which the script depends.
> fix(package.js): fix installation of dependent libraries

- src/lib/apmJson.js
- src/migration/migration1to2.js
- src/renderer/main/core.js
- Change not to make `apm.json` when changing the installation path to an empty directory.
> fix: change not to make apm.json when changing the installation path

- src/renderer/main/core.js
- src/renderer/main/package.js
When scripts.json is read, if it has not already been downloaded, it will be downloaded.
1. Change the path of the dataURL. (The update date of scripts.json must be the same or older than before the change.)
2. The list of script download sites will no longer be displayed.
- The bug has been fixed.
> fix(package.js): ensure script data is loaded

- src/lib/modList.ts
- src/renderer/main/core.js
- src/renderer/main/package.js
- src/renderer/main/setting.ts
Fix bugs related to `list.json`.
- An error occurs when starting apm with a clean install.
- This is because `getInfo()` is executed before `list.json` is downloaded.
- If I change apm-data to `main` branch after loading https://github.com/team-apm/apm-data/pull/182 , I get an error that test/khsk-packages.json cannot be loaded.
- This is because the list of packages in the electron-store is not updated when the new `list.json` is downloaded.
- Ensure that the above bugs are not occurring.
> fix: fix bugs related to list.json

- src/renderer/main/core.js
If `exedit.auf` is placed in the `plugins` folder, apm will corrupt the existing environment. This PR will prevent such a folder from being selected.
- If `Exedit` exists in the `plugins` folder, apm cannot move to that installation folder.
> fix(core.js): detect location of exedit.auf

- src/renderer/main/packageUtil.js
Make `.lua` files recognized as AviUtl-related files. This allows us to detect manual installations of libraries that contain only lua files. Currently only `shummg/dotdrawer` and `shummg/shuGame` are affected by this change.
- https://github.com/team-apm/apm-data/pull/274
- Automatically detects installed shummg/shuGame.
> feat(packageUtil.js): recognize lua files as AviUtl-related files

- src/migration/migration1to2.ts
- src/renderer/main/package.ts
Refactor for the future removal and for fixing of the warning.
- Remove `fs.rmdir` for the future removal.
- Change to named imports in `migration1to2.ts`.
> Refactor for future removal the warning

- forge.config.ts
- package.json
- src/renderer/main/index.html
- src/renderer/main/package.ts
- yarn.lock
Remove the non-working Twemoji library. See #1078.
- fixes #1078
- Confirmed that standard Windows emojis are displayed.
> feat(twemoji): remove non-working Twemoji

- src/lib/unzip.ts
Fix a bug that prevented .7z files from being unzipped.
- #1188
- Motion Tracking MK-II can be installed.
> fix(unzip.ts): no codepoint when unzipping .7z

- src/main.ts
Crashing when `destory()` a browser window with child browser windows. To prevent crashes, change to close it in the regular procedure.
- closes #1423
- You can install `PNG出力（バグ修正版）`, which opens a new `about:blank` window when downloading the zip file.
> fix: safely close the window

- package.json
- src/main.ts
- src/renderer/main.css
- src/renderer/main/core.ts
- src/renderer/main/index.css
- src/renderer/main/index.html
- src/renderer/main/package.ts
- src/renderer/main/preload.ts
- src/renderer/main/renderer.ts
- yarn.lock
Dark themes are now supported as standard from Bootstrap 5.3. Remove bootstrap-dark-5 and CSS that have finished their role.
It also includes minor fixes to button design and wording.
This PR depends on
- #1498
- Check the visibility in the dark theme.
> feat: update darktheme

- src/renderer/main/core.ts
- src/renderer/main/packageUtil.ts
おすすめインストールボタンを押したとき、パッケージのファイルが不足している場合でも再インストールが行われない問題を修正します。また、ファイルが不足している場合のメッセージをapmの内部動作と矛盾のない表現に変更します。
https://github.com/team-apm/apm-data/issues/638#issuecomment-1878355360 参照
InputPipePluginのパッケージデータに"lwinput64.aui"を追加した場合、apmの"AviUtl"タブに「未インストール（ファイルの存在が確認できませんでした。）」と表示されてしまう問題があります。
このPRでメッセージが分かりやすくなり、対処も容易になります。
> fix(core): allow reinstallation of broken package

- src/renderer/main/packageUtil.ts
match() returns null for strings that do not match the regex. This time, the cause was a package id such as `script_a1d871c` generated by the automatic script installation.
- fix #1969
- No error occurs with the reproduction procedure https://github.com/team-apm/apm/issues/1969  .
> fix(packageUtil): match() may return null
